config/routes.rb
Rails.application.routes.draw do
  resources :newspapers

end

app/models/newspaper.rb
require 'nokogiri'
require 'open-uri'

class Newspaper < ActiveRecord::Base
  validates :name, presence: true
  validates :feed, presence: true
  Struct.new("Article", :title, :intro, :content)

  def articles
    res = Array.new()
    article_links(feed).each do |link|
      res << parse_article(link)
    end

    return res
  end

  private 

  def pages(link)
    doc = Nokogiri::HTML(open(link))

    pages = Array.new()

    doc.css("a.link-gradient-button").each do |anchor|
      pages << anchor['href']
    end

    return pages
  end

  def article_links(link)
    doc = Nokogiri::HTML(open(link))
    links = Array.new()
    doc.css(".search-teaser > a").each do |anchor|
      links << anchor['href'] if anchor['href'].include?("http://www.spiegel.de") 
    end

    return links 
  end

  def parse_article(link)
    doc = Nokogiri::HTML(open(link)) 
    article = Struct::Article.new('','','')

    doc.css(".article-title *").each do |child|
      article.title += child.content
    end

    article.intro = doc.css(".article-intro").first.content

    doc.css(".article-section.clearfix p").each do |p|
      article.content += p.content
    end

    return article
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/newspapers_controller.rb
class NewspapersController < ApplicationController
  before_action :set_newspaper, only: [:show, :edit, :update, :destroy]

  # GET /newspapers
  # GET /newspapers.json
  def index
    @newspapers = Newspaper.all
  end

  # GET /newspapers/1
  # GET /newspapers/1.json
  def show
    @articles = @newspaper.articles
  end

  # GET /newspapers/new
  def new
    @newspaper = Newspaper.new
  end

  # GET /newspapers/1/edit
  def edit
  end

  # POST /newspapers
  # POST /newspapers.json
  def create
    @newspaper = Newspaper.new(newspaper_params)

    respond_to do |format|
      if @newspaper.save
        format.html { redirect_to @newspaper, notice: 'Newspaper was successfully created.' }
        format.json { render :show, status: :created, location: @newspaper }
      else
        format.html { render :new }
        format.json { render json: @newspaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newspapers/1
  # PATCH/PUT /newspapers/1.json
  def update
    respond_to do |format|
      if @newspaper.update(newspaper_params)
        format.html { redirect_to @newspaper, notice: 'Newspaper was successfully updated.' }
        format.json { render :show, status: :ok, location: @newspaper }
      else
        format.html { render :edit }
        format.json { render json: @newspaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newspapers/1
  # DELETE /newspapers/1.json
  def destroy
    @newspaper.destroy
    respond_to do |format|
      format.html { redirect_to newspapers_url, notice: 'Newspaper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newspaper
      @newspaper = Newspaper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newspaper_params
      params.require(:newspaper).permit(:name, :publisher, :feed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/newspapers_helper.rb
module NewspapersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wyt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/newspapers/_form.html.erb
<%= form_for(@newspaper) do |f| %>
  <% if @newspaper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@newspaper.errors.count, "error") %> prohibited this newspaper from being saved:</h2>

      <ul>
      <% @newspaper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br>
    <%= f.text_field :publisher %>
  </div>
  <div class="field">
    <%= f.label :feed %><br>
    <%= f.text_field :feed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/newspapers/edit.html.erb
<h1>Editing Newspaper</h1>

<%= render 'form' %>

<%= link_to 'Show', @newspaper %> |
<%= link_to 'Back', newspapers_path %>

app/views/newspapers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Newspapers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Publisher</th>
      <th>Feed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @newspapers.each do |newspaper| %>
      <tr>
        <td><%= newspaper.name %></td>
        <td><%= newspaper.publisher %></td>
        <td><%= newspaper.feed %></td>
        <td><%= link_to 'Show', newspaper %></td>
        <td><%= link_to 'Edit', edit_newspaper_path(newspaper) %></td>
        <td><%= link_to 'Destroy', newspaper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Newspaper', new_newspaper_path %>

app/views/newspapers/new.html.erb
<h1>New Newspaper</h1>

<%= render 'form' %>

<%= link_to 'Back', newspapers_path %>

app/views/newspapers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @newspaper.name %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @newspaper.publisher %>
</p>

<p>
  <strong>Feed:</strong>
  <%= @newspaper.feed %>
</p>

<% @articles.each do |article|%>
  <h1><%= article.title %></h1>
  <p><%= article.intro %></p>
  <p><%= article.content %></p>
<% end %>
<%= link_to 'Edit', edit_newspaper_path(@newspaper) %> |
<%= link_to 'Back', newspapers_path %>